---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.1 には、いくつかの新機能と機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.10.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.1 には、いくつかの新機能と機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== C4、M4、およびR4のインスタンスはサポートされなくなりました（2022年10月28日）

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。



== 9.10.1 P6（2022年7月13日）

バージョン3.9.19以降を実行するコネクタがある場合、Microsoft Azureで9.10.1 P6パッチがCloud Volumes ONTAP で利用できるようになりました。既存のシステムのこのパッチリリースへのアップグレードを求めるプロンプトが Cloud Manager に表示されます。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.10.1P6["P6 パッチで修正されたバグのリストを表示します"^] （NetApp Support Siteへのログインが必要です）。



== 9.10.1 P3（2022年5月15日）

バージョン3.9.13以降を実行しているコネクタがある場合、Microsoft Azureで9.10.1 P3パッチがCloud Volumes ONTAP で使用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.10.1P3["P3 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== ライセンスに関する更新情報（ 2022 年 2 月 9 日）

市場における Cloud Volumes ONTAP の変更点を次に示します。

* Essentials パッケージと Professional パッケージが AWS と Google Cloud Marketplace で利用できるようになりました。
+
容量単位の課金方法では、時間単位での支払いや、年間契約の購入をクラウドプロバイダから直接行うことができます。容量単位のライセンスは、ネットアップから直接購入することもできます。

+
クラウドマーケットプレイスで既存のサブスクリプションがある場合は、それらの新しいサービスにも自動的にサブスクライブされます。新しい Cloud Volumes ONTAP 作業環境の導入時に、容量単位の課金を選択できます。

+
新規のお客様の場合は、新しい作業環境を作成するときに登録を求めるメッセージが表示されます。

* AWS と Google Cloud Marketplace を使用したノード単位のライセンスは廃止され、新しいユーザには提供されなくなりました。これには、年間契約と時間単位のサブスクリプション（ Explore 、 Standard 、 Premium ）が含まれます。
+
この充電方法は、有効なサブスクリプションをお持ちの既存のお客様には引き続きご利用いただけます。



link:concept-licensing.html["Cloud Volumes ONTAP のライセンスオプションの詳細については、こちらをご覧ください"]。



== 9.10.1 GA （ 2022 年 1 月 31 日）

Cloud Volumes ONTAP 9.10.1 の General Availability （ GA ）リリースがリリースされました。GA リリースにはバグの修正が含まれています。

BlueXPでは、9.10.1 RC1、9.10.0、または9.0.1のいずれかのバージョンを実行している既存のシステムをアップグレードするように求められます。



== その他の VM タイプ（ 2021 年 1 月 2 日）のサポート

BlueXP 3.9.14リリースの一部として、Cloud Volumes ONTAP は9.10.1リリース以降のMicrosoft Azureで次のVMタイプでサポートされるようになりました。

* E4ds_v4
* E8ds_v4
* E32ds_v4
* E48ds_v4


にアクセスします link:reference-configs-azure.html["[ サポートされている構成 ] ページ"] 詳細：



== 9.10.1 RC1 （ 2021 年 11 月 28 日）

Cloud Volumes ONTAP 9.10.1 Release Candidate 1 が AWS 、 Azure 、 Google Cloud で提供されるようになりました。このリリースには、次の新機能と機能拡張が含まれています。



=== Microsoft Azure の HA 機能が強化されました

* Microsoft Azure で実行される Cloud Volumes ONTAP HA ペアの計画外フェイルオーバー時間を短縮しました。
* NFSv4 がサポートされるようになりました。


これらの機能拡張を Cloud Volumes ONTAP で利用できるようにするには、 Azure サブスクリプションで機能を有効にする必要があります。「 Owner 」権限のある Azure ユーザは、 Azure CLI からこの機能を有効にできます。

[source, azurecli]
----
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
----
Cloud Volumes ONTAP 9.10.1システムでは、Azureサブスクリプションでこの機能を有効にする必要がある場合、これらの詳細を「Action Required」メッセージで表示するように求められます。

次の点に注意してください。

* Cloud Volumes ONTAP HA ペアの高可用性に問題はありません。この Azure 機能は、 ONTAP と連携して動作し、計画外のフェイルオーバーによって発生する NFS プロトコルのアプリケーション停止時間を短縮します。
* この機能を有効にしても、 Cloud Volumes ONTAP HA ペアの処理は中断されません。
* Azure サブスクリプションでこの機能を有効にしても、他の VM で原因の問題は発生しません。




=== セキュリティの機能拡張

ONTAP イメージ作成のセキュリティを強化し、 Cloud Volumes ONTAP ブートディスクのセキュリティを強化しました。



=== Keystone Flex Subscriptions をサポート

コネクタ3.9.13リリースの一部として、Cloud Volumes ONTAP HAペアでKeystone Flexサブスクリプションを使用できるようになりました。Keystone Flex サブスクリプションは、成長に合わせて購入できるサブスクリプションベースのサービスです。 OPEX 消費モデルを希望するお客様に、設備投資やリースを先に行うお客様にシームレスなハイブリッドクラウドエクスペリエンスを提供します。

Keystone Flexサブスクリプションは、BlueXPから導入できるすべての新しいバージョンのCloud Volumes ONTAP でサポートされています。



=== 暗号化キー管理

ONTAP 9.10.1 リリースには、 Azure Key Vault （ AKV ）または Google Cloud Key Management Service を使用した ONTAP 暗号化キーの保護を可能にする機能拡張が含まれています。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-security.html["Cloud Volumes ONTAP の暗号化のサポートについては、こちらをご覧ください"^]。



== 必要なBlueXPコネクタのバージョン

新しいCloud Volumes ONTAP 9.10.1システムを導入し、既存のシステムを9.10.1にアップグレードするには、BlueXP Connectorがバージョン3.9.13以降を実行している必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



== アップグレードに関する注意事項

* Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性
* 9.10.0 リリースから Cloud Volumes ONTAP 9.10.1 にアップグレードしたり、 9.9.1 リリースからアップグレードしたりできます。BlueXPでは、対象となるCloud Volumes ONTAP システムを9.10.1リリースにアップグレードするように求められます。
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== DS3_v2 の場合

9.9.1 リリース以降では、 DS3_v2 VM タイプは新規および既存の Cloud Volumes ONTAP システムでサポートされなくなりました。この VM タイプで既存のシステムを実行している場合は、 9.10.1 にアップグレードする前に VM タイプを変更する必要があります。
